### ISSUE TITLE
Triggers with Papers Please

### ISSUE THREAD

**Issue by Will-Nichols** [Task-Force-Red/Operation-Tanoa-Takedown#3]
@Jmaster9999 Can you help with this aspect? Want to make sure that the sqf's will function as intended with the triggers.

**Comment by Will-Nichols** [comment]
@Jmaster9999 you going to jump in and help on this or should I ask someone else to take a look?

**Comment by Jmaster9999** [comment]
I'm busy with school work and all my dev time is going towards DayZ stuff right now, I can answer questions if you want but I'm not really able to do much other than that.

**Comment by Will-Nichols** [comment]
Never mind I'll figure it out.

**Comment by Will-Nichols** [comment]
closing and moving all parts to #5 issue.
