### ISSUE TITLE
Loadout script not working correctly

### ISSUE THREAD

**Issue by coachwn** [Task-Force-Red/Operation-Tanoa-Takedown#4]
Created loadouts and they work almost the first time.

Issues are as follows.

Kutu slots and Firehawk 1-1 do not spawn in with pistols.

Wagen tested Kutu 6 and when he got shot the first time he respawned with the default Syndikat loadout instead of what is scripted.

**Comment by Scotty-Z** [comment]
found the bug
you had it like this: **nul = [this,"loadoutName"] execVM "loadouts\SFBreacher.sqf";**
when is should be like this: **nul = [this,"SFBreacher"] execVM "loadouts\createLoadout.sqf";**

**Comment by coachwn** [comment]
Yeah discovered that AFTER @Jmaster9999 had given me the previous one when I had an issue with the other...something got lost in translation.
