### ISSUE TITLE
Thinking of adding in this script to the mission

### ISSUE THREAD

**Issue by Will-Nichols** [Task-Force-Red/Operation-Tanoa-Takedown#8]
[https://forums.bohemia.net/forums/topic/217470-release-ace-punish-unknownenemy-weapon-script/](url)

**Comment by Scotty-Z** [comment]
you can do the same thing with dzn Extended Jamming by making specific weapons have a higher chance of jamming

**Comment by Will-Nichols** [comment]
dzn is a pain in my ass....I really am not a big fan of his stuff.
